// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: getFeedById.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedById = `-- name: GetFeedById :one
SELECT id, created_at, updated_at, name, url, user_id
FROM feeds
WHERE id = $1
`

func (q *Queries) GetFeedById(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedById, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
